### ISSUE TITLE
jnius问题

### ISSUE THREAD

**Issue by huasheng-yue** [nkiiiiid/kivy-apk-#11]
启动后,测试jniushello目录下的main.py
在该目录下进入命令行,运行: python3 main.py 失败, 提示如下:
kivydev@kivydev-VirtualBox:~/test/jniushello$ python3 main.py
[INFO   ] [Logger      ] Record log in /home/kivydev/.kivy/logs/kivy_20-06-26_13.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/python37/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.1 (default, Apr 28 2020, 20:55:30) 
[GCC 5.4.0 20160609]
[INFO   ] [Python      ] Interpreter at "/usr/local/python37/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     from jnius import *
 ModuleNotFoundError: No module named 'jnius'
kivydev@kivydev-VirtualBox:~/test/jniushello$

**Comment by huasheng-yue** [comment]
No module named 'jnius'

**Comment by huasheng-yue** [comment]
尝试安装jnius-1.1.0.tar.gz失败：
(kivyenv) PS C:\Users\hsytr> pip install D:\Anaconda\pkgs\jnius-1.1.0.tar.gz
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Processing d:\anaconda\pkgs\jnius-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hsytr\\AppData\\Local\\Temp\\pip-req-build-qje4uhaf\\setup.py'"'"'; __file__='"'"'C:\\Users\\hsytr\\AppData\\Local\\Temp\\pip-req-build-qje4uhaf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\hsytr\AppData\Local\Temp\pip-pip-egg-info-d308rgy5'
         cwd: C:\Users\hsytr\AppData\Local\Temp\pip-req-build-qje4uhaf\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hsytr\AppData\Local\Temp\pip-req-build-qje4uhaf\setup.py", line 111, in <module>
        raise Exception('Unable to determine JDK_HOME')
    Exception: Unable to determine JDK_HOME
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(kivyenv) PS C:\Users\hsytr>

**Comment by nkiiiiid** [comment]
all the example are used for package test，don't run it on computer，especially the libs used for Android system such as jnius
